export const language = {
  verificationSucessfull: [
    "Verification Successful",
    "በተሳካ ሁኔታ ተረጋግጧል",
    "",
    "",
    "",
    "",
  ],
  securityLookout: [
    "Security Lockout: Too many failed attempts. Try again in 1 hour.",
    "የደህንነት እገዳ፡ ሙከራዎ በዝቷል። እባክዎን ከ1 ሰዓት በኋላ እንደገና ይሞክሩ።",
  ],
  noRecordFound: ["No Record Found", "", "", "", "", ""],
  attemptsLeft: ["attempts left", "ቀሪ ሙከራዎች", "", "", "", "", ""],
  verificationResultWillAppear: [
    "Verification results will appear here",
    "የማረጋገጫ ውጤቶች እዚህ ይታያሉ",
    "",
    "",
    "",
  ],
  filloutVerify: [
    "Please fill out the form and click verify",
    "እባክዎን ቅጹን ይሙሉ እና 'አረጋግጥ' የሚለውን ይጫኑ",
    "",
    "",
    "",
    "",
  ],
  bankAccountNumber: ["Bank Account Number", "የባንክ ቁጥር", "", "", "", ""],
  enterAccountNumber: [
    "Enter Account Number",
    "ሂሳብ ቁጥርዎን ያስገቡ",
    "",
    "",
    "",
    "",
    "",
  ],
  locked: ["Locked", "ታጉዳል", "", "", "", ""],
  attemptsRemaining: ["Attempts Remaining", "የቀሩ ሙከራዎች", "", "", "", "", ""],
  recordVerifiedSuccess: [
    "Record Verified Successfully",
    "መዝገቡ በስኬት ተረጋግጧል",
    "",
    "",
    "",
    "",
  ],
  bankAccount: ["Bank Account", "የባንክ ቁጥር", "", "", "", "", ""],
  fullname: ["Full Name", "ሙሉ ስም", "", "", "", "", ""],
  programType: ["Program Type", "የፕሮግራም አይነት", "", "", "", ""],
  verifyAnotherRecord: [
    "Verify Another Record",
    "ሌላ መዝገብ አረጋግጥ",
    "",
    "",
    "",
    "",
    "",
  ],
  noSavingRecord: [
    "We couldn't find a savings record matching this account number. Please check the digits and try again.",
    "ከዚህ የሂሳብ ቁጥር ጋር የሚዛመድ የቁጠባ መዝገብ ማግኘት አልተቻለም። እባክዎን ቁጥሮቹን አረጋግጠው እንደገና ይሞክሩ።",
    "",
    "",
    "",
    "",
  ],
  tryAgain: ["Try different details", "እንደገና ይሞክሩ", "", "", "", ""],
  confirmedRecord: ["Confirm Record", "የተረጋገጡ መዝገቦች", "", "", "", "", ""],
  noSavingInfo:["Use this link for missing information","መረጃ ያላገኛችሁ በዚህ ሊንክ ተጠቀሙ"]
};
